baseURL = "https://starttls-everywhere.org/"
languageCode = "en-us"
title = "STARTTLS Everywhere"
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
[params]
  APIHostname = "http://localhost:8080"
